### ISSUE TITLE
Training times

### ISSUE THREAD

**Issue by dvidgar** [dairui01/PDAN#4]
Hi Rui,
I've just come across PDAN today. It looks promising, a really good job. 
I couldn't find any information about the training times on your V100, can you share this info? I don't have access to such a good GPUs anymore, only a rtx 2080... I will consider if it makes sense for me to run your code, with the 480p Charades dataset.
Thanks in advance.

**Comment by dairui01** [comment]
Hi, 
Thank you for your interest in this work. 
As our model is built on top of the extracted I3D features, the computation requirement is not harsh. 
I just tried running PDAN on a single RTX2080 Ti and there is no memory issue. I can get a promising result in a couple of hours. For sure, a better GPU can shrink the computation time. 

But, before running PDAN, you need to extract the I3D feature first. With one RTX 2080 GPU, I don't think you can extract the same feature as the default setting. This is because you need to change the window size due to the limited memory. This change may hamper the final detection result. Moreover, we utilize the _RGB frames at 24 fps_ rather than the _480p_ from their website. That can also cause a difference in the final result. 

Let me know if you still need any other info.

**Comment by dvidgar** [comment]
Hi Rui,

Everything is clear now, I will give PDAN a try. 
Could you share your I3D features then? I see that extracting them will be very time-consuming and plus, the final detection results will not be as good as expected.

Thanks for your help.

**Comment by dairui01** [comment]
I can not share the I3D features as I don't have enough space on my local machine and cloud disk to save those features online. 
But those features are extracted exactly the same follow the repository that I provided in the readme. So you need to find another way to have those features. 
Sorry for the inconvenience.

**Comment by dvidgar** [comment]
Could you share at least one example of the I3D features? At least one .npy file? 

Eventually, I used this [this repo](https://github.com/GowthamGottimukkala/I3D_Feature_Extraction_resnet) to extract the I3D features in my GPU and the dimensions don't match with you code. For example, the shape of DOLQ1 is (4, 10, 2048). 
I changed the input_channnel from 1024 to 2048 but I don't understand what to do with the other two dimensions.
Thank you for your help.

**Comment by dairui01** [comment]
The repository you cited is not the one I provide in the README. That's why it has a mismatch with the dimension. 
Please utilize the [pytoch-i3d](https://github.com/piergiaj/pytorch-i3d) to extract the feature and reproduce the numbers in the paper. 

BTW, I don't think the dimension you provided here is correct. The first dimension "4" is very misleading, I guess it should be batch but how the batch can be 4 for a single video. 

In this work, the feature accepted by PDAN should be a T x H x W x D feature. If the feature is after the AVG Pool, then H and W could be 1. 
Also, please note that if you are using an I3D with Resnet50 backbone (the one you cited), so it is not fair to compare with the other methods, such as Super event, TGM, PDAN, MLAD using the vanilla-I3D (the repository I provided).
